### ISSUE TITLE
Crash in outpost war

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#152]
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055bb4ffb9c11 in CAIAliasDescriptionNode::fullName[abi:cxx11]() const ()
[Current thread is 1 (Thread 0x7fea67b48740 (LWP 13029))]
```

```
(gdb) backtrace
#0  0x000055bb4ffb9c11 in CAIAliasDescriptionNode::fullName[abi:cxx11]() const ()
#1  0x000055bb4ffec2c9 in CStateInstance::processStateEvent(CAIEvent const&, CAIState const*) ()
#2  0x000055bb501c4671 in CPersistentStateInstance::updateStateInstance() ()
#3  0x000055bb50025143 in COutpost::createSquad(CGroupDesc<COutpostSquadFamily> const*, COutpostSquadManager*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, COutpostSpawnZone const*, unsigned int, unsigned int, OUTPOSTENUMS::TPVPSide) ()
#4  0x000055bb50026489 in COutpost::createSquad(unsigned int, unsigned int, unsigned int, unsigned int, OUTPOSTENUMS::TPVPSide) ()
#5  0x000055bb5002682b in cbOutpostCreateSquad(NLNET::CMessage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, NLNET::TServiceId) ()
#6  0x000055bb50218763 in CMirror::updateMirrorAndReceiveMessages(NLNET::CMessage&) ()
#7  0x000055bb502191a8 in cbUpdateMirrorAndReceiveMessages(NLNET::CMessage&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, NLNET::TServiceId) ()
#8  0x000055bb503bc1e2 in NLNET::uncbMsgProcessing(NLNET::CMessage&, NLNET::CBufSock*, NLNET::CCallbackNetBase&) ()
#9  0x000055bb503891ce in NLNET::CCallbackNetBase::processOneMessage() ()
#10 0x000055bb50389a92 in NLNET::CCallbackNetBase::baseUpdate2(int, int) ()
#11 0x000055bb503882e4 in NLNET::CCallbackClient::update2(int, int) ()
#12 0x000055bb503c0613 in NLNET::CUnifiedNetwork::update(long) ()
#13 0x000055bb4ff73352 in NLNET::IService::main(char const*, char const*, unsigned short, char const*, char const*, char const*) ()
#14 0x000055bb4ff65359 in main ()
(gdb)
```

**Comment by kaetemi** [comment]
```
2020/10/04 12:00:03 DBG 1739884352 AIS-142 ai_outpost.cpp 796 createSquad : Creating a squad
```

**Comment by kaetemi** [comment]
- [x] Restart Zorai AIS on Momo with debug build
- [x] Test again in the same way

**Comment by kaetemi** [comment]
- [ ] Test again in release mode

**Comment by kaetemi** [comment]
```
2020/10/24 15:00:04 DBG 380081984 AIS-141 ai_outpost.cpp 796 createSquad : Creating a squad
2020/10/24 15:00:04 DBG 380081984 AIS-141 state_instance.h 508 processStateEvent : Reaction for event
2020/10/24 15:00:04 INF 380081984 AIS-141 script_vm.cpp 809 interpretCode : CREATING A SQUAD
2020/10/24 15:00:04 DBG 380081984 AIS-141 ai_outpost.cpp 897 createSquad : Outpost outpost_zorai_02: squad created defending 0x0 against 0x25900001, respawnTime=864000 gc
2020/10/24 15:00:07 DBG 380081984 AIS-141 ai_outpost.cpp 902 spawnSquad : Outpost outpost_zorai_02: Spawning squad 0x9ffab1f0
2020/10/24 15:00:07 DBG 380081984 AIS-141 ai_outpost.cpp 920 spawnSquad : 		Spawned
2020/10/24 15:00:10 DBG 380081984 AIS-141 state_instance.h 534 processStateEvent : No reaction for event
2020/10/24 15:05:05 DBG 380081984 AIS-141 ai_outpost.cpp 970 deleteSquad : Outpost outpost_zorai_02: deleting squad 0x9ffab1f0
2020/10/24 15:05:05 DBG 380081984 AIS-141 state_instance.h 534 processStateEvent : No reaction for event
2020/10/24 15:05:05 DBG 380081984 AIS-141 ai_outpost.cpp 796 createSquad : Creating a squad
2020/10/24 15:05:05 DBG 380081984 AIS-141 state_instance.h 508 processStateEvent : Reaction for event
2020/10/24 15:05:05 INF 380081984 AIS-141 script_vm.cpp 809 interpretCode : CREATING A SQUAD
2020/10/24 15:05:05 DBG 380081984 AIS-141 ai_outpost.cpp 897 createSquad : Outpost outpost_zorai_02: squad created defending 0x0 against 0x25900001, respawnTime=864000 gc
2020/10/24 15:05:08 DBG 380081984 AIS-141 ai_outpost.cpp 902 spawnSquad : Outpost outpost_zorai_02: Spawning squad 0x9ffab1f0
2020/10/24 15:05:08 DBG 380081984 AIS-141 ai_outpost.cpp 920 spawnSquad : 		Spawned
2020/10/24 15:05:11 DBG 380081984 AIS-141 state_instance.h 534 processStateEvent : No reaction for event
2020/10/24 15:10:06 DBG 380081984 AIS-141 ai_outpost.cpp 970 deleteSquad : Outpost outpost_zorai_02: deleting squad 0x9ffab1f0
2020/10/24 15:10:06 DBG 380081984 AIS-141 state_instance.h 534 processStateEvent : No reaction for event
2020/10/24 15:10:06 DBG 380081984 AIS-141 ai_outpost.cpp 796 createSquad : Creating a squad
2020/10/24 15:10:06 DBG 380081984 AIS-141 state_instance.h 508 processStateEvent : Reaction for event
2020/10/24 15:10:06 INF 380081984 AIS-141 script_vm.cpp 809 interpretCode : CREATING A SQUAD
2020/10/24 15:10:06 DBG 380081984 AIS-141 ai_outpost.cpp 897 createSquad : Outpost outpost_zorai_02: squad created defending 0x0 against 0x25900001, respawnTime=864000 gc
2020/10/24 15:10:09 DBG 380081984 AIS-141 ai_outpost.cpp 902 spawnSquad : Outpost outpost_zorai_02: Spawning squad 0x9ffab1f0
2020/10/24 15:10:09 DBG 380081984 AIS-141 ai_outpost.cpp 920 spawnSquad : 		Spawned
2020/10/24 15:10:10 DBG 380081984 AIS-141 state_instance.h 534 processStateEvent : No reaction for event
```
