### ISSUE TITLE
assert ai_entity_physical_inline.h 78

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#22]
May be a racing condition when the EGS crashes upon player connection.
```
A failed assertion occurs
ProcName: AIS-134
Date: 2019/11/18 10:11:30
File: /mnt/y/ryzomclassic/code/ryzom/server/src/ai_service/ai_entity_physical_inline.h
Line: 78
FuncName: CAIEntityPhysical
Reason: "CAIS::instance()._CAIEntityByDataSetRow.find(entityIndex.getIndex())==CAIS::instance()._CAIEntityByDataSetRow.end()" 
Dumping call stack :
0 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN6NLMISC12getCallStackERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x5b) [0x5569c8c53c3c]
1 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN6NLMISC18getCallStackAndLogERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x30) [0x5569c8c53d6e]
2 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN6NLMISC4CLog13displayStringEPKc+0x373) [0x5569c8c91d7f]
3 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN6NLMISC4CLog9displayNLEPKcz+0x177) [0x5569c8c92021]
4 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN17CAIEntityPhysicalC2ER21CPersistentOfPhysicalRK11TDataSetRowRKN6NLMISC9CEntityIdEfjRKN15RYAI_MAP_CRUNCH10TAStarFlagE+0x637) [0x5569c87b4a2f]
5 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN10CBotPlayerC1EP14CManagerPlayerRK11TDataSetRowRKN6NLMISC9CEntityIdEj+0x9c) [0x5569c88806ba]
6 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN14CManagerPlayer16addSpawnedPlayerERK11TDataSetRowRKN6NLMISC9CEntityIdE+0x41) [0x5569c8881def]
7 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN8CMirrors20processMirrorUpdatesEv+0x14e) [0x5569c89db5a2]
8 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN7CMirror30updateMirrorAndReceiveMessagesERN5NLNET8CMessageE+0x284) [0x5569c8b08e56]
9 : /home/nevrax/classic/live/service_ai_service/ai_service(_Z32cbUpdateMirrorAndReceiveMessagesRN5NLNET8CMessageERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_10TServiceIdE+0x2d) [0x5569c8b08b83]
10 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN5NLNET17uncbMsgProcessingERNS_8CMessageEPNS_8CBufSockERNS_16CCallbackNetBaseE+0x729) [0x5569c8d5074e]
11 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN5NLNET16CCallbackNetBase17processOneMessageEv+0x6cd) [0x5569c8d04381]
12 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN5NLNET16CCallbackNetBase11baseUpdate2Eii+0x162) [0x5569c8d048b4]
13 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN5NLNET15CCallbackClient7update2Eii+0xab) [0x5569c8d032c3]
14 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN5NLNET15CUnifiedNetwork6updateEl+0xe13) [0x5569c8d543bf]
15 : /home/nevrax/classic/live/service_ai_service/ai_service(_ZN5NLNET8IService4mainEPKcS2_tS2_S2_S2_+0x4a2b) [0x5569c8d36df7]
16 : /home/nevrax/classic/live/service_ai_service/ai_service(main+0xeb) [0x5569c8a639fd]
17 : /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fb68e209b97]
18 : /home/nevrax/classic/live/service_ai_service/ai_service(_start+0x2a) [0x5569c8735dda]
-------------------------------

Log with no filter:
-------------------------------
2019/11/18 10:10:34 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:35 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:36 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:37 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:37 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:38 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:38 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:38 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:10:39 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:10:39 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:10:39 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:39 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:39 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:10:39 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:10:39 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:10:40 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:40 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:10:40 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:10:41 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:42 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:46 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:47 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:48 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:49 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:49 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:50 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:10:50 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:50 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:51 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:51 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:10:59 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:11:01 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:02 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:03 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:10 AIS-134 DBG 8e7d7780 ai_profile_npc.cpp 967 : ==> max bots visible is now 65
2019/11/18 10:11:10 AIS-134 DBG 8e7d7780 ai_profile_npc.cpp 968 : vision time: 0.17
2019/11/18 10:11:10 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:11:13 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:13 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:11:14 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:15 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:11:15 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:25 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:26 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:27 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:28 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:29 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:29 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:11:29 AIS-134 WRN 8e7d7780 unified_network.cpp 357 : HNETL5: Can't find callback 'IMPULSION_ID' called by service 132
2019/11/18 10:11:30 AIS-134 WRN 8e7d7780 ai_profile_npc.cpp 4198 : Follow No Path : NPC bot 'forge_apprentice_pyr'
2019/11/18 10:11:30 AIS-134 AST 8e7d7780 ai_entity_physical_inline.h 78 : "CAIS::instance()._CAIEntityByDataSetRow.find(entityIndex.getIndex())==CAIS::instance()._CAIEntityByDataSetRow.end()" 
-------------------------------
```

**Comment by kaetemi** [comment]
Another occurrence after login. Maybe mission related?
```
#0  0x000055c1d65eea2f in CAIEntityPhysical::CAIEntityPhysical (this=0x55c1e107dd10, owner=..., entityIndex=..., id=..., radius=0.5, level=1, AStarFlags=@0x7ffe1397f380: RYAI_MAP_CRUNCH::Nothing)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/ai_service/ai_entity_physical_inline.h:78
#1  0x000055c1d66ba6ba in CBotPlayer::CBotPlayer (this=0x55c1e107dcc0, owner=0x55c1dabbbd80, DataSetRow=..., id=..., level=1) at /mnt/y/ryzomclassic/code/ryzom/server/src/ai_service/ai_player.cpp:36
#2  0x000055c1d66bbdef in CManagerPlayer::addSpawnedPlayer (this=0x55c1dabbbd80, dataSetRow=..., id=...) at /mnt/y/ryzomclassic/code/ryzom/server/src/ai_service/ai_player.cpp:280
#3  0x000055c1d68155a2 in CMirrors::processMirrorUpdates () at /mnt/y/ryzomclassic/code/ryzom/server/src/ai_service/mirrors.cpp:191
#4  0x000055c1d6942e56 in CMirror::updateMirrorAndReceiveMessages (this=0x55c1d723dd40 <CMirrors::Mirror>, msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2125
#5  0x000055c1d6942b83 in cbUpdateMirrorAndReceiveMessages (msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2074
#6  0x000055c1d6b8a74e in NLNET::uncbMsgProcessing (msgin=..., from=0x55c1dab69a10) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#7  0x000055c1d6b3e381 in NLNET::CCallbackNetBase::processOneMessage (this=0x55c1dab698a0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#8  0x000055c1d6b3e8b4 in NLNET::CCallbackNetBase::baseUpdate2 (this=0x55c1dab698a0, timeout=35, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#9  0x000055c1d6b3d2c3 in NLNET::CCallbackClient::update2 (this=0x55c1dab698a0, timeout=35, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_client.cpp:128
#10 0x000055c1d6b8e3bf in NLNET::CUnifiedNetwork::update (this=0x55c1d8c25840, timeout=100) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1078
#11 0x000055c1d6b70df7 in NLNET::IService::main (this=0x55c1d8c1ed00, serviceShortName=0x55c1d6ce2565 "AIS", serviceLongName=0x55c1d6ce255a "ai_service", servicePort=0, configDir=0x55c1d6ce2322 "", logDir=0x55c1d6ce2322 "",
    compilationDate=0x55c1d6ce2569 "Nov 18 2019 11:07:26") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#12 0x000055c1d689d9fd in main (argc=6, argv=0x7ffe13980318) at /mnt/y/ryzomclassic/code/ryzom/server/src/ai_service/service_main.cpp:359

```

**Comment by kaetemi** [comment]
May be related with the NeL service duplicate UP/DOWN message bug that has been fixed.
