### ISSUE TITLE
Missing log context for player sale items

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#23]
```
A failed assertion occurs
ProcName: EGS-134
Date: 2019/11/18 10:15:58
File: /mnt/y/ryzomclassic/code/ryzom/server/src/server_share/log_item_gen.cpp
Line: 1432
FuncName: _log_Item_Delete
Reason: STOP
Dumping call stack :
0 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN6NLMISC12getCallStackERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x5b) [0x55dd1796bdde]
1 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN6NLMISC18getCallStackAndLogERNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0x30) [0x55dd1796bf10]
2 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN6NLMISC4CLog13displayStringEPKc+0x373) [0x55dd179b6583]
3 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN6NLMISC4CLog9displayNLEPKcz+0x177) [0x55dd179b6825]
4 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN6NLMISC16_assertex_stop_0ERbiPKcS2_S2_+0x127) [0x55dd1796bcf1]
5 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN6NLMISC12_assert_stopERbiPKcS2_S2_+0x39) [0x55dd1796bd75]
6 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_Z16_log_Item_DeleteN11INVENTORIES7TItemIdERKN6NLMISC8CSheetIdEjjPKcj+0x282) [0x55dd178d637c]
7 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN9CGameItem10deleteItemEPS_+0x3fd) [0x55dd17030143]
8 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN12CGameItemPtr10deleteItemEv+0x22b) [0x55dd1702d781]
9 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN12CItemForSaleD1Ev+0x47) [0x55dd17581695]
10 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN12CItemForSaleD0Ev+0x18) [0x55dd175816f2]
11 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN6NLMISC9CSmartPtrI10IItemTradeEaSEPS1_+0x79) [0x55dd17579d3d]
12 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN6NLMISC9CSmartPtrI10IItemTradeEaSERKS2_+0x26) [0x55dd175793e6]
13 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN13CItemsForSale14checkSellStoreEN6NLMISC9CEntityIdE+0x1a1) [0x55dd17585879]
14 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN10CCharacter14checkSellStoreEv+0x52) [0x55dd173c9990]
15 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_Z19finalizeClientReadyjj+0xcf5) [0x55dd1700e53b]
16 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN24COfflineCharacterCommand27COfflineCommandFileCallback8callbackERK16CFileDescriptionRN6NLMISC7IStreamE+0x64) [0x55dd1758c7d6]
17 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(+0x1c3813c) [0x55dd1760513c]
18 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN5NLNET17uncbMsgProcessingERNS_8CMessageEPNS_8CBufSockERNS_16CCallbackNetBaseE+0x729) [0x55dd17a79e06]
19 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN5NLNET16CCallbackNetBase17processOneMessageEv+0x6cd) [0x55dd17a3272f]
20 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN5NLNET16CCallbackNetBase11baseUpdate2Eii+0x162) [0x55dd17a32c62]
21 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN5NLNET15CCallbackClient7update2Eii+0xab) [0x55dd17a31671]
22 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN5NLNET15CUnifiedNetwork6updateEl+0xe13) [0x55dd17a7da77]
23 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_ZN5NLNET8IService4mainEPKcS2_tS2_S2_S2_+0x4a2b) [0x55dd17a61d2f]
24 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(main+0xeb) [0x55dd16d749a2]
25 : /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fe6a992ab97]
26 : /home/nevrax/classic/live/service_entities_game_service/entities_game_service(_start+0x2a) [0x55dd16c351da]
-------------------------------

Log with no filter:
-------------------------------
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 31 : LOADED User '2' Character 'Ulygrikos(Momo)' from BS stream file 'characters/002/account_2_2_pdr.bin'
2019/11/18 10:15:34 EGS-134 DBG a9ef8780 fixed_size_int_vector.h 122 : CFixedSizeDataVector_resize allocating a new buffer of size 7227 x 8 (5 buffers in all)
2019/11/18 10:15:34 EGS-134 DBG a9ef8780 fixed_size_int_vector.h 122 : CFixedSizeDataVector_resize allocating a new buffer of size 7227 x 2 (5 buffers in all)
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 30 : <CCharacter::searchCreateRoleSheet> Selected sheet: fyros_craftsman.starting_role
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 30 : <CCharacter::searchCreateRoleSheet> Selected sheet: fyros_harvester.starting_role
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 30 : <CCharacter::searchCreateRoleSheet> Selected sheet: fyros_magician.starting_role
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 30 : <CCharacter::searchCreateRoleSheet> Selected sheet: fyros_fighter.starting_role
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 31 : LOADED User '2' Character 'Deuntis(Momo)' from BS stream file 'characters/002/account_2_3_pdr.bin'
2019/11/18 10:15:34 EGS-134 DBG a9ef8780 fixed_size_int_vector.h 122 : CFixedSizeDataVector_resize allocating a new buffer of size 7227 x 8 (6 buffers in all)
2019/11/18 10:15:34 EGS-134 DBG a9ef8780 fixed_size_int_vector.h 122 : CFixedSizeDataVector_resize allocating a new buffer of size 7227 x 2 (6 buffers in all)
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 24 : Increased item vector size to 7808 items (3060736 bytes)
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 30 : <CCharacter::searchCreateRoleSheet> Selected sheet: fyros_craftsman.starting_role
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 30 : <CCharacter::searchCreateRoleSheet> Selected sheet: fyros_harvester.starting_role
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 30 : <CCharacter::searchCreateRoleSheet> Selected sheet: fyros_magician.starting_role
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 30 : <CCharacter::searchCreateRoleSheet> Selected sheet: fyros_fighter.starting_role
2019/11/18 10:15:34 EGS-134 INF a9ef8780 egs_log_filter.h 31 : LOADED User '2' Character 'Ioperirus(Momo)' from BS stream file 'characters/002/account_2_4_pdr.bin'
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail0_AutoSN at 8348.706055 -10369.618164 0.000000 with RM m0109dxacb01.sitem, quantity 11.6605 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail1_AutoSN at 8357.233398 -10485.324219 0.000000 with RM m0109dxacb01.sitem, quantity 13.1105 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail2_AutoSN at 8496.190430 -10665.015625 0.000000 with RM m0109dxacb01.sitem, quantity 12.7313 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail3_AutoSN at 8397.092773 -10694.858398 0.000000 with RM m0109dxacb01.sitem, quantity 15.1598 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail4_AutoSN at 8326.250977 -10832.449219 0.000000 with RM m0109dxacb01.sitem, quantity 13.0748 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail6_AutoSN at 8439.359375 -10361.916016 0.000000 with RM m0109dxacb01.sitem, quantity 12.4615 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail7_AutoSN at 8357.276367 -10545.004883 0.000000 with RM m0109dxacb01.sitem, quantity 14.2985 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail8_AutoSN at 8426.501953 -10929.851562 0.000000 with RM m0109dxacb01.sitem, quantity 13.7767 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail9_AutoSN at 8503.342773 -10901.083984 0.000000 with RM m0109dxacb01.sitem, quantity 14.8843 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail10_AutoSN at 8544.410156 -10315.379883 0.000000 with RM m0109dxacb01.sitem, quantity 15.6312 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail11_AutoSN at 8498.322266 -10617.016602 0.000000 with RM m0109dxacb01.sitem, quantity 13.3425 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail12_AutoSN at 8304.933594 -10739.798828 0.000000 with RM m0109dxacb01.sitem, quantity 11.8137 (validation pending)
2019/11/18 10:15:35 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in kitins_marker_trail13_AutoSN at 8576.697266 -10890.345703 0.000000 with RM m0109dxacb01.sitem, quantity 18.3304 (validation pending)
2019/11/18 10:15:36 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_fyros_mission_1_1 at 21199.656250 -25536.718750 0.000000 with RM m0103dxacb01.sitem, quantity 11.8043 (validation pending)
2019/11/18 10:15:36 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_fyros_mission_1_2 at 22018.431641 -26154.853516 0.000000 with RM m0103dxacb01.sitem, quantity 14.7121 (validation pending)
2019/11/18 10:15:36 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_fyros_mission_1_3 at 22426.587891 -25511.003906 0.000000 with RM m0109dxacb01.sitem, quantity 12.0651 (validation pending)
2019/11/18 10:15:36 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_fyros_mission_1_4 at 21512.156250 -26657.757812 0.000000 with RM m0109dxacb01.sitem, quantity 15.7179 (validation pending)
2019/11/18 10:15:36 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_fyros_mission_1_5 at 22782.009766 -26624.869141 0.000000 with RM m0103dxacb01.sitem, quantity 12.9041 (validation pending)
2019/11/18 10:15:36 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_starting_city_A3_AutoSN at 10173.540039 -11791.185547 0.000000 with RM m0113dxacb01.sitem, quantity 15.5351 (validation pending)
2019/11/18 10:15:38 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in fyros_imperialdunes_0-50_beng_amber at 18974.701172 -24391.695312 0.000000 with RM m0015dxacc01.sitem, quantity 12.8367 (validation pending)
2019/11/18 10:15:40 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_starting_city_A5_AutoSN at 10358.763672 -11451.180664 0.000000 with RM m0113dxacb01.sitem, quantity 10.0644 (validation pending)
2019/11/18 10:15:43 EGS-134 INF a9ef8780 player_manager.cpp 1234 : set active char 4 for player 2
2019/11/18 10:15:43 EGS-134 INF a9ef8780 egs_log_filter.h 25 : Mapping UID 2 => Sid (0x0000000024:00:00:85)
2019/11/18 10:15:43 EGS-134 INF a9ef8780 logger_service_client.cpp 194 : LGS : log : Character_Select : A character has been selected to play, userId = 2, charId = (0x0000000024:00:00:85), charName = Ioperirus(Momo)
2019/11/18 10:15:43 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_starting_city_B2_AutoSN at 10490.341797 -11614.371094 0.000000 with RM m0119dxacb01.sitem, quantity 18.5419 (validation pending)
2019/11/18 10:15:47 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_starting_city_B1_AutoSN at 10195.755859 -11627.931641 0.000000 with RM m0053dxacb01.sitem, quantity 12.9537 (validation pending)
2019/11/18 10:15:47 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_starting_city_B5 at 10190.887695 -11897.139648 0.000000 with RM m0053dxacb01.sitem, quantity 17.6265 (validation pending)
2019/11/18 10:15:52 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_starting_city_B5_OLDMISSION at 10223.366211 -11773.951172 0.000000 with RM m0119dxacb01.sitem, quantity 16.9793 (validation pending)
2019/11/18 10:15:57 EGS-134 DBG a9ef8780 fg_prospection_phrase.cpp 1186 : FG: Source auto-spawned in newbieland_starting_city_A4_AutoSN at 10511.403320 -11784.627930 0.000000 with RM m0662dxacb01.sitem, quantity 16.6397 (validation pending)
2019/11/18 10:15:58 EGS-134 DBG a9ef8780 entity_callbacks.cpp 438 : Setting player (0x0000000024:00:00:85) in instance #3 for continent 'unknown'
2019/11/18 10:15:58 EGS-134 INF a9ef8780 egs_log_filter.h 25 : Client ready (entity (0x0000000024:00:00:85) (Row 90502) added to mirror)
2019/11/18 10:15:58 EGS-134 DBG a9ef8780 shard_unifier_client.cpp 1081 : Uni : connectionEvents: receive 1 connection event
2019/11/18 10:15:58 EGS-134 DBG a9ef8780 shard_unifier_client.cpp 1090 :   Char (0x0000000024:00:00:00) has connected
2019/11/18 10:15:58 EGS-134 WRN a9ef8780 log_item_gen.cpp 1432 : /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp(1875) : Missing log context for log 'Item'
2019/11/18 10:15:58 EGS-134 AST a9ef8780 log_item_gen.cpp 1432 : STOP
-------------------------------

```

**Comment by kaetemi** [comment]
```
#0  0x000055dd178d6384 in _log_Item_Delete (itemId=..., sheetId=..., quantity=10, quality=5, _filename_=0x55dd17bacee0 "/mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp",
    _lineNo_=1875) at /mnt/y/ryzomclassic/code/ryzom/server/src/server_share/log_item_gen.cpp:1432
#1  0x000055dd17030143 in CGameItem::deleteItem (item=0x55dd2c322938) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:1875
#2  0x000055dd1702d781 in CGameItemPtr::deleteItem (this=0x55dd2c5b2768) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:752
#3  0x000055dd17581695 in CItemForSale::~CItemForSale (this=0x55dd2c5b2700, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/item_for_sale.cpp:48
#4  0x000055dd175816f2 in CItemForSale::~CItemForSale (this=0x55dd2c5b2700, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/item_for_sale.cpp:51
#5  0x000055dd17579d3d in NLMISC::CSmartPtr<IItemTrade>::operator= (this=0x55dd2c5b2a20, p=0x55dd1ae04e20) at /mnt/y/ryzomclassic/code/nel/include/nel/misc/smart_ptr_inline.h:87
#6  0x000055dd175793e6 in NLMISC::CSmartPtr<IItemTrade>::operator= (this=0x55dd2c5b2a20, p=...) at /mnt/y/ryzomclassic/code/nel/include/nel/misc/smart_ptr_inline.h:98
#7  0x000055dd17585879 in CItemsForSale::checkSellStore (this=0x55dd2c5ab660, charId=...) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/items_for_sale.cpp:127
#8  0x000055dd173c9990 in CCharacter::checkSellStore (this=0x55dd2c55b080) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:10196
#9  0x000055dd1700e53b in finalizeClientReady (userId=2, index=4) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entity_manager/entity_callbacks.cpp:667
#10 0x000055dd1758c7d6 in COfflineCharacterCommand::COfflineCommandFileCallback::callback (this=0x55dd24317850, fileDescription=..., dataStream=...)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/offline_character_command.cpp:173
#11 0x000055dd1760513c in cbFile (msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/_backup_service_interface_non_module.cpp:204
#12 0x000055dd17a79e06 in NLNET::uncbMsgProcessing (msgin=..., from=0x55dd1899b7e0) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#13 0x000055dd17a3272f in NLNET::CCallbackNetBase::processOneMessage (this=0x55dd189bddd0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#14 0x000055dd17a32c62 in NLNET::CCallbackNetBase::baseUpdate2 (this=0x55dd189bddd0, timeout=98, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#15 0x000055dd17a31671 in NLNET::CCallbackClient::update2 (this=0x55dd189bddd0, timeout=98, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_client.cpp:128
#16 0x000055dd17a7da77 in NLNET::CUnifiedNetwork::update (this=0x55dd18943050, timeout=99) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1078
#17 0x000055dd17a61d2f in NLNET::IService::main (this=0x55dd1893b2e0, serviceShortName=0x55dd17b6bee1 "EGS", serviceLongName=0x55dd17b6becb "entities_game_service", servicePort=0, configDir=0x55dd17b6b504 "",
    logDir=0x55dd17b6b504 "", compilationDate=0x55dd17b6bee5 "Nov 18 2019 11:02:20") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#18 0x000055dd16d749a2 in main (argc=5, argv=0x7ffe33e3d8a8) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:2138
```
