### ISSUE TITLE
EGS log context missing when buying from player

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#26]
```
#0  0x000055dd9193b472 in _log_Item_Delete (itemId=..., sheetId=..., quantity=1, quality=10, _filename_=0x55dd91c12180 "/mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp",
    _lineNo_=1875) at /mnt/y/ryzomclassic/code/ryzom/server/src/server_share/log_item_gen.cpp:1464
#1  0x000055dd910952e3 in CGameItem::deleteItem (item=0x55dda7847a30) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:1875
#2  0x000055dd91092921 in CGameItemPtr::deleteItem (this=0x55dd9feb32d8) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:752
#3  0x000055dd915e66a5 in CItemForSale::~CItemForSale (this=0x55dd9feb3270, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/item_for_sale.cpp:48
#4  0x000055dd915e6702 in CItemForSale::~CItemForSale (this=0x55dd9feb3270, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/item_for_sale.cpp:51
#5  0x000055dd90f133a3 in NLMISC::CSmartPtr<IItemTrade>::~CSmartPtr (this=0x55dda19dd188, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/nel/include/nel/misc/smart_ptr_inline.h:72
#6  0x000055dd915ddffc in CCharacterShoppingList::TShopStruct::~TShopStruct (this=0x55dda19dd188, __in_chrg=<optimized out>)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/character_shopping_list.h:41
#7  0x000055dd915e24db in std::_Destroy<CCharacterShoppingList::TShopStruct> (__pointer=0x55dda19dd188) at /usr/include/c++/8/bits/stl_construct.h:98
#8  0x000055dd915e1553 in std::_Destroy_aux<false>::__destroy<CCharacterShoppingList::TShopStruct*> (__first=0x55dda19dd188, __last=0x55dda19dd1b8) at /usr/include/c++/8/bits/stl_construct.h:108
#9  0x000055dd915dfb3a in std::_Destroy<CCharacterShoppingList::TShopStruct*> (__first=0x55dda19dd0e0, __last=0x55dda19dd1b8) at /usr/include/c++/8/bits/stl_construct.h:137
#10 0x000055dd915dee29 in std::_Destroy<CCharacterShoppingList::TShopStruct*, CCharacterShoppingList::TShopStruct> (__first=0x55dda19dd0e0, __last=0x55dda19dd1b8) at /usr/include/c++/8/bits/stl_construct.h:206
#11 0x000055dd915dee8e in std::vector<CCharacterShoppingList::TShopStruct, std::allocator<CCharacterShoppingList::TShopStruct> >::_M_erase_at_end (this=0x55dd9fb04528, __pos=0x55dda19dd0e0)
    at /usr/include/c++/8/bits/stl_vector.h:1658
#12 0x000055dd915de4a2 in std::vector<CCharacterShoppingList::TShopStruct, std::allocator<CCharacterShoppingList::TShopStruct> >::clear (this=0x55dd9fb04528) at /usr/include/c++/8/bits/stl_vector.h:1386
#13 0x000055dd915d7638 in CCharacterShoppingList::~CCharacterShoppingList (this=0x55dd9fb044e0, __in_chrg=<optimized out>)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/character_shopping_list.cpp:62
#14 0x000055dd91432a9b in CCharacter::endBotChat (this=0x55dda77bc0f0, newBotChat=false, closeDynChat=false) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:10845
#15 0x000055dd90d3d29a in cbClientBotChatEnd (msgin=..., serviceName="FS", serviceId=...) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/client_messages.cpp:1879
#16 0x000055dd91702a35 in CMirror::updateMirrorAndReceiveMessages (this=0x55dd92510580 <Mirror>, msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2170
#17 0x000055dd91702309 in cbUpdateMirrorAndReceiveMessages (msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2074
#18 0x000055dd91adf0aa in NLNET::uncbMsgProcessing (msgin=..., from=0x55dd9ece9030) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#19 0x000055dd91a979d3 in NLNET::CCallbackNetBase::processOneMessage (this=0x55dd9ed01770) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#20 0x000055dd91a97f06 in NLNET::CCallbackNetBase::baseUpdate2 (this=0x55dd9ed01770, timeout=56, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#21 0x000055dd91a96915 in NLNET::CCallbackClient::update2 (this=0x55dd9ed01770, timeout=56, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_client.cpp:128
#22 0x000055dd91ae2d1b in NLNET::CUnifiedNetwork::update (this=0x55dd939f32a0, timeout=99) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1078
#23 0x000055dd91ac6fd3 in NLNET::IService::main (this=0x55dd939eb530, serviceShortName=0x55dd91bd1181 "EGS", serviceLongName=0x55dd91bd116b "entities_game_service", servicePort=0, configDir=0x55dd91bd07a4 "",
    logDir=0x55dd91bd07a4 "", compilationDate=0x55dd91bd1185 "Nov 18 2019 20:03:25") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#24 0x000055dd90dd9b42 in main (argc=5, argv=0x7ffd9e08dbb8) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:2138

```

**Comment by kaetemi** [comment]
Added context log, but there shouldn't be any item deletion going on there.
There seems to be some temporary item duplication going on in a shopping list structure here.
