### ISSUE TITLE
EGS crash on harvest item, recursing temp inv close

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#31]
Old known bug...
```
#0  0x00005627d17491bf in CCharacter::sendCloseTempInventoryImpulsion (this=0x5627e843ebe0) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:14483
#1  0x00005627d1725c34 in CCharacter::endHarvest (this=0x5627e843ebe0, sendCloseTempImpulsion=true) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:7957
#2  0x00005627d17a7691 in CCharacter::itemTempInventoryToBag (this=0x5627e843ebe0, srcSlot=0, sendCloseTempImpulsion=false)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character_inventory_manipulation.cpp:1862
#3  0x00005627d17a9347 in CCharacter::getAllTempInventoryItems (this=0x5627e843ebe0, sendCloseTempImpulsion=false)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character_inventory_manipulation.cpp:2109
#4  0x00005627d17491dc in CCharacter::sendCloseTempInventoryImpulsion (this=0x5627e843ebe0) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:14486
#5  0x00005627d1725c34 in CCharacter::endHarvest (this=0x5627e843ebe0, sendCloseTempImpulsion=true) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:7957
#6  0x00005627d172530e in CCharacter::harvestAsked (this=0x5627e843ebe0, mpIndex=0, quantity=65535) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:7845
#7  0x00005627d179eb97 in CCharacter::itemPickup (this=0x5627e843ebe0, entity=..., harvest=true) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character_inventory_manipulation.cpp:429
#8  0x00005627d1381117 in cbItemPickup (msgin=..., serviceName="FS", serviceId=...) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entity_manager/entity_callbacks.cpp:2569
#9  0x00005627d1de30aa in NLNET::uncbMsgProcessing (msgin=..., from=0x5627dfc13b40) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#10 0x00005627d1d9b9d3 in NLNET::CCallbackNetBase::processOneMessage (this=0x5627dfc139d0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#11 0x00005627d1d9bf06 in NLNET::CCallbackNetBase::baseUpdate2 (this=0x5627dfc139d0, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#12 0x00005627d1d9a915 in NLNET::CCallbackClient::update2 (this=0x5627dfc139d0, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_client.cpp:128
#13 0x00005627d1de6d1b in NLNET::CUnifiedNetwork::update (this=0x5627d49032a0, timeout=100) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1078
#14 0x00005627d1dcafd3 in NLNET::IService::main (this=0x5627d48fb530, serviceShortName=0x5627d1ed5181 "EGS", serviceLongName=0x5627d1ed516b "entities_game_service", servicePort=0, configDir=0x5627d1ed47a4 "",
    logDir=0x5627d1ed47a4 "", compilationDate=0x5627d1ed5185 "Nov 18 2019 20:03:25") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#15 0x00005627d10ddb42 in main (argc=5, argv=0x7ffd6d911038) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:2138
```
```
2019/11/19 02:53:55 EGS-134 INF 00bc3780 logger_service_client.cpp 215 : LGS : Open log context 'Item_Forage'
2019/11/19 02:53:55 EGS-134 WRN 00bc3780 character.cpp 14483 : CCharacter::sendCloseTempInventoryImpulsion is recursing!
2019/11/19 02:53:55 EGS-134 AST 00bc3780 character.cpp 14483 : STOP
```

**Comment by kaetemi** [comment]
Wonder if this is related to the stumbling double "end forage" animation state that sometimes occurs.
