### ISSUE TITLE
EGS context log missing when enchanting right hand item

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#37]
```
#0  0x000055f50ab3901c in _log_Item_Delete (itemId=..., sheetId=..., quantity=1, quality=1, _filename_=0x55f50ae0fd20 "/mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp",
    _lineNo_=1875) at /mnt/y/ryzomclassic/code/ryzom/server/src/server_share/log_item_gen.cpp:1497
#1  0x000055f50a292baf in CGameItem::deleteItem (item=0x55f51b269468) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:1875
#2  0x000055f50a2901ed in CGameItemPtr::deleteItem (this=0x7ffcd9ca08a0) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:752
#3  0x000055f50a2b9470 in CInventoryBase::deleteItem (this=0x55f51b5336c0, slot=10) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/player_inventory.cpp:337
#4  0x000055f50a6a78e7 in CCharacter::enchantItem (this=0x55f521cc32a0, invId=INVENTORIES::bag, slot=10)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character_inventory_manipulation.cpp:2745
#5  0x000055f50a6a6320 in CCharacter::enchantOrRechargeItem (this=0x55f521cc32a0, invId=INVENTORIES::bag, slot=10)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character_inventory_manipulation.cpp:2610
#6  0x000055f509f32944 in cbClientItemEnchant (msgin=..., serviceName="FS", serviceId=...) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/client_messages.cpp:297
#7  0x000055f50a900549 in CMirror::updateMirrorAndReceiveMessages (this=0x55f50b70d3e0 <Mirror>, msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2170
#8  0x000055f50a8ffe1d in cbUpdateMirrorAndReceiveMessages (msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2074
#9  0x000055f50acdce1e in NLNET::uncbMsgProcessing (msgin=..., from=0x55f518d40e00) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#10 0x000055f50ac95747 in NLNET::CCallbackNetBase::processOneMessage (this=0x55f518d40c90) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#11 0x000055f50ac95c7a in NLNET::CCallbackNetBase::baseUpdate2 (this=0x55f518d40c90, timeout=87, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#12 0x000055f50ac94689 in NLNET::CCallbackClient::update2 (this=0x55f518d40c90, timeout=87, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_client.cpp:128
#13 0x000055f50ace0a8f in NLNET::CUnifiedNetwork::update (this=0x55f50da2a280, timeout=100) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1078
#14 0x000055f50acc4d47 in NLNET::IService::main (this=0x55f50da22510, serviceShortName=0x55f50adcece1 "EGS", serviceLongName=0x55f50adceccb "entities_game_service", servicePort=0, configDir=0x55f50adce304 "",
    logDir=0x55f50adce304 "", compilationDate=0x55f50adcece5 "Nov 19 2019 15:46:27") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#15 0x000055f509fd7094 in main (argc=5, argv=0x7ffcd9ca1848) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:2138
```

**Comment by kaetemi** [comment]
Still occurring.

**Comment by kaetemi** [comment]
Also crashing when creating sap crystal. Probably crashes when using sap crystal as well.
```
#0  0x000055a358d55a0e in _log_Item_Money (moneyBefore=100000, moneyAfter=99750,
    _filename_=0x55a3590dc700 "/mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp", _lineNo_=10274)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/server_share/log_item_gen.cpp:1570
#1  0x000055a3588487a1 in CCharacter::setMoney (this=0x55a36e3c0dd0, money=@0x7ffd9769fa98: 99750)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:10274
#2  0x000055a358848711 in CCharacter::spendMoney (this=0x55a36e3c0dd0, price=@0x7ffd9769fb00: 250)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:10251
#3  0x000055a35878a41b in CMagicActionItemCharge::apply (this=0x55a3679e0660, phrase=0x55a36b3085c0, deltaLevel=-230, skillLevel=20, successFactor=0.698026299, behav=...,
    powerFactors=std::vector of length 1, capacity 1 = {...}, affectedTargets=..., invulnerabilityOffensive=..., invulnerabilityAll=..., isMad=false, resists=..., actionReport=..., vamp=0,
    vampRatio=1, reportXp=true) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/phrase_manager/magic_action_item_charge.cpp:105
#4  0x000055a358797723 in CMagicPhrase::apply (this=0x55a36b3085c0) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/phrase_manager/magic_phrase.cpp:1695
#5  0x000055a3587af7e8 in CPhraseManager::updateEntityCurrentAction (this=0x55a35a67e360, entityId=..., entityPhrases=...)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/phrase_manager/phrase_manager.cpp:551
#6  0x000055a3587af286 in CPhraseManager::updatePhrases (this=0x55a35a67e360) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/phrase_manager/phrase_manager.cpp:463
#7  0x000055a3581ea69f in CPlayerService::egsUpdate () at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:738
#8  0x000055a358b2249e in CMirror::onTick (this=0x55a3599293e0 <Mirror>) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.h:650
#9  0x000055a358b1cbfd in cbTickUpdateFunc () at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2280
#10 0x000055a358c4a64d in CTickEventHandler::tickUpdate (serviceId=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/tick_event_handler.cpp:181
#11 0x000055a358c4a3f1 in cbTick (msgin=..., serviceName="MS", serviceId=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/tick_event_handler.cpp:111
#12 0x000055a358ef8e4c in NLNET::uncbMsgProcessing (msgin=..., from=0x55a36588f750) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#13 0x000055a358eb1775 in NLNET::CCallbackNetBase::processOneMessage (this=0x55a36588f5e0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#14 0x000055a358eb1ca8 in NLNET::CCallbackNetBase::baseUpdate2 (this=0x55a36588f5e0, timeout=98, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#15 0x000055a358eb06b7 in NLNET::CCallbackClient::update2 (this=0x55a36588f5e0, timeout=98, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_client.cpp:128
#16 0x000055a358efcabd in NLNET::CUnifiedNetwork::update (this=0x55a35a57af10, timeout=99) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1078
#17 0x000055a358ee0d75 in NLNET::IService::main (this=0x55a35a5735c0, serviceShortName=0x55a358fead01 "EGS", serviceLongName=0x55a358feaceb "entities_game_service", servicePort=0,
    configDir=0x55a358fea324 "", logDir=0x55a358fea324 "", compilationDate=0x55a358fead05 "Nov 20 2019 10:17:33") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#18 0x000055a3581f30a4 in main (argc=5, argv=0x7ffd976a0b08) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:2138
```
