### ISSUE TITLE
EGS context log crash buying player item

### ISSUE THREAD

**Issue by kaetemi** [kaetemi/ryzomclassic#44]
```
#0  0x000055c47c70101c in _log_Item_Delete (itemId=..., sheetId=..., quantity=4, quality=5, _filename_=0x55c47c9d7d20 "/mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp",
    _lineNo_=1875) at /mnt/y/ryzomclassic/code/ryzom/server/src/server_share/log_item_gen.cpp:1497
#1  0x000055c47be5abaf in CGameItem::deleteItem (item=0x55c49175b0f8) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:1875
#2  0x000055c47be581ed in CGameItemPtr::deleteItem (this=0x55c491744fa8) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:752
#3  0x000055c47c3ac1b9 in CItemForSale::~CItemForSale (this=0x55c491744f40, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/item_for_sale.cpp:48
#4  0x000055c47c3ac216 in CItemForSale::~CItemForSale (this=0x55c491744f40, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/item_for_sale.cpp:51
#5  0x000055c47bcd8c69 in NLMISC::CSmartPtr<IItemTrade>::~CSmartPtr (this=0x55c4924b1ed0, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/nel/include/nel/misc/smart_ptr_inline.h:72
#6  0x000055c47c3a3b10 in CCharacterShoppingList::TShopStruct::~TShopStruct (this=0x55c4924b1ed0, __in_chrg=<optimized out>)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/character_shopping_list.h:41
#7  0x000055c47c3a7fef in std::_Destroy<CCharacterShoppingList::TShopStruct> (__pointer=0x55c4924b1ed0) at /usr/include/c++/8/bits/stl_construct.h:98
#8  0x000055c47c3a7067 in std::_Destroy_aux<false>::__destroy<CCharacterShoppingList::TShopStruct*> (__first=0x55c4924b1ed0, __last=0x55c4924b1f30) at /usr/include/c++/8/bits/stl_construct.h:108
#9  0x000055c47c3a564e in std::_Destroy<CCharacterShoppingList::TShopStruct*> (__first=0x55c4924b1ed0, __last=0x55c4924b1f30) at /usr/include/c++/8/bits/stl_construct.h:137
#10 0x000055c47c3a493d in std::_Destroy<CCharacterShoppingList::TShopStruct*, CCharacterShoppingList::TShopStruct> (__first=0x55c4924b1ed0, __last=0x55c4924b1f30) at /usr/include/c++/8/bits/stl_construct.h:206
#11 0x000055c47c3a49a2 in std::vector<CCharacterShoppingList::TShopStruct, std::allocator<CCharacterShoppingList::TShopStruct> >::_M_erase_at_end (this=0x55c4901193e8, __pos=0x55c4924b1ed0)
    at /usr/include/c++/8/bits/stl_vector.h:1658
#12 0x000055c47c3a3fb6 in std::vector<CCharacterShoppingList::TShopStruct, std::allocator<CCharacterShoppingList::TShopStruct> >::clear (this=0x55c4901193e8) at /usr/include/c++/8/bits/stl_vector.h:1386
#13 0x000055c47c39d14c in CCharacterShoppingList::~CCharacterShoppingList (this=0x55c4901193a0, __in_chrg=<optimized out>)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/character_shopping_list.cpp:62
#14 0x000055c47c1ed165 in CCharacter::startTradeItemSession (this=0x55c493035fd0, session=8) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:9097
#15 0x000055c47c223cc3 in CCharacter::refreshTradeList (this=0x55c493035fd0) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:19881
#16 0x000055c47c1ed876 in CCharacter::setFilters (this=0x55c493035fd0, minQuality=0, maxQuality=300, minPrice=0, maxPrice=999999999, minClass=RM_CLASS_TYPE::Basic, maxClass=RM_CLASS_TYPE::Supreme,
    itemPartFilter=RM_FABER_TYPE::MPRE, itemTypeFilter=ITEM_TYPE::UNDEFINED) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:9191
#17 0x000055c47bb02481 in cbClientBotChatSetFilters (msgin=..., serviceName="FS", serviceId=...) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/client_messages.cpp:1845
#18 0x000055c47c4c8549 in CMirror::updateMirrorAndReceiveMessages (this=0x55c47d2d53e0 <Mirror>, msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2170
#19 0x000055c47c4c7e1d in cbUpdateMirrorAndReceiveMessages (msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2074
#20 0x000055c47c8a4e1e in NLNET::uncbMsgProcessing (msgin=..., from=0x55c48a845b40) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#21 0x000055c47c85d747 in NLNET::CCallbackNetBase::processOneMessage (this=0x55c48a8459d0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#22 0x000055c47c85dc7a in NLNET::CCallbackNetBase::baseUpdate2 (this=0x55c48a8459d0, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#23 0x000055c47c85c689 in NLNET::CCallbackClient::update2 (this=0x55c48a8459d0, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_client.cpp:128
#24 0x000055c47c8a8a8f in NLNET::CUnifiedNetwork::update (this=0x55c47f531280, timeout=100) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1078
#25 0x000055c47c88cd47 in NLNET::IService::main (this=0x55c47f529510, serviceShortName=0x55c47c996ce1 "EGS", serviceLongName=0x55c47c996ccb "entities_game_service", servicePort=0, configDir=0x55c47c996304 "",
    logDir=0x55c47c996304 "", compilationDate=0x55c47c996ce5 "Nov 19 2019 15:46:27") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#26 0x000055c47bb9f094 in main (argc=5, argv=0x7ffde8e40fd8) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:2138

```

**Comment by kaetemi** [comment]
Related to #26

**Comment by kaetemi** [comment]
Also when paying out to player.
```
#0  0x000055880a686990 in _log_Item_Money (moneyBefore=14817, moneyAfter=15401, _filename_=0x55880aa0d6e0 "/mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp", _lineNo_=10272)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/server_share/log_item_gen.cpp:1571
#1  0x000055880a179727 in CCharacter::setMoney (this=0x558820fc4e80, money=@0x7ffc62e118a8: 15401) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:10272
#2  0x000055880a1796d6 in CCharacter::giveMoney (this=0x558820fc4e80, money=@0x7ffc62e118f8: 584) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:10260
#3  0x000055880a178b76 in CCharacter::itemSolded (this=0x558820fc4e80, identifier=27, quantity=4, sellPrice=246, basePrice=100, buyer=..., sellOffline=true)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character.cpp:10163
#4  0x000055880a33cb42 in CSoldItem::apply (this=0x558818f9eb50, offlineCommand=true) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/offline_character_command.cpp:257
#5  0x000055880a33c3e8 in COfflineCharacterCommand::COfflineCommandFileCallback::callback (this=0x55881dccdb80, fileDescription=..., dataStream=...)
    at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/offline_character_command.cpp:188
#6  0x000055880a3b4ca8 in cbFile (msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/_backup_service_interface_non_module.cpp:204
#7  0x000055880a829e1e in NLNET::uncbMsgProcessing (msgin=..., from=0x55880d468a10) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#8  0x000055880a7e2747 in NLNET::CCallbackNetBase::processOneMessage (this=0x55880d48b000) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#9  0x000055880a7e2c7a in NLNET::CCallbackNetBase::baseUpdate2 (this=0x55880d48b000, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#10 0x000055880a7e1689 in NLNET::CCallbackClient::update2 (this=0x55880d48b000, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_client.cpp:128
#11 0x000055880a82da8f in NLNET::CUnifiedNetwork::update (this=0x55880d410280, timeout=99) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1078
#12 0x000055880a811d47 in NLNET::IService::main (this=0x55880d408510, serviceShortName=0x55880a91bce1 "EGS", serviceLongName=0x55880a91bccb "entities_game_service", servicePort=0, configDir=0x55880a91b304 "",
    logDir=0x55880a91b304 "", compilationDate=0x55880a91bce5 "Nov 19 2019 15:46:27") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#13 0x0000558809b24094 in main (argc=5, argv=0x7ffc62e12798) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:2138
```

**Comment by kaetemi** [comment]
another one
```
#0  0x000055c80f0c5072 in _log_Item_Delete (itemId=..., sheetId=..., quantity=4, quality=5, _filename_=0x55c80f39bd20 "/mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp",
    _lineNo_=1875) at /mnt/y/ryzomclassic/code/ryzom/server/src/server_share/log_item_gen.cpp:1496
#1  0x000055c80e81ebbf in CGameItem::deleteItem (item=0x55c822825738) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:1875
#2  0x000055c80e81c1fd in CGameItemPtr::deleteItem (this=0x55c82280f548) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/game_item_manager/game_item.cpp:752
#3  0x000055c80ed7020f in CItemForSale::~CItemForSale (this=0x55c82280f4e0, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/item_for_sale.cpp:48
#4  0x000055c80ed7026c in CItemForSale::~CItemForSale (this=0x55c82280f4e0, __in_chrg=<optimized out>) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/item_for_sale.cpp:51
#5  0x000055c80ed688b7 in NLMISC::CSmartPtr<IItemTrade>::operator= (this=0x55c81cf31090, p=0x55c822810980) at /mnt/y/ryzomclassic/code/nel/include/nel/misc/smart_ptr_inline.h:87
#6  0x000055c80ed67f60 in NLMISC::CSmartPtr<IItemTrade>::operator= (this=0x55c81cf31090, p=...) at /mnt/y/ryzomclassic/code/nel/include/nel/misc/smart_ptr_inline.h:98
#7  0x000055c80ed6e97a in CDynamicItems::tickUpdate (this=0x55c8227823a0) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/shop_type/dynamic_items.cpp:425
#8  0x000055c80e55af38 in CPlayerService::egsUpdate () at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:805
#9  0x000055c80ee92476 in CMirror::onTick (this=0x55c80fc993e0 <Mirror>) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.h:650
#10 0x000055c80ee8cbd5 in cbTickUpdateFunc () at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2280
#11 0x000055c80efba625 in CTickEventHandler::tickUpdate (serviceId=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/tick_event_handler.cpp:181
#12 0x000055c80efba3c9 in cbTick (msgin=..., serviceName="MS", serviceId=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/tick_event_handler.cpp:111
#13 0x000055c80f268e24 in NLNET::uncbMsgProcessing (msgin=..., from=0x55c8105f02c0) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#14 0x000055c80f22174d in NLNET::CCallbackNetBase::processOneMessage (this=0x55c8105f0150) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#15 0x000055c80f221c80 in NLNET::CCallbackNetBase::baseUpdate2 (this=0x55c8105f0150, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#16 0x000055c80f22068f in NLNET::CCallbackClient::update2 (this=0x55c8105f0150, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_client.cpp:128
#17 0x000055c80f26ca95 in NLNET::CUnifiedNetwork::update (this=0x55c81062ef10, timeout=100) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1078
#18 0x000055c80f250d4d in NLNET::IService::main (this=0x55c8106275c0, serviceShortName=0x55c80f35ace1 "EGS", serviceLongName=0x55c80f35accb "entities_game_service", servicePort=0, configDir=0x55c80f35a304 "",
    logDir=0x55c80f35a304 "", compilationDate=0x55c80f35ace5 "Nov 20 2019 10:17:33") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#19 0x000055c80e5630a4 in main (argc=5, argv=0x7ffeb6850c68) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:2138
```
