### ISSUE TITLE
Server crashes after trading with a player

### ISSUE THREAD

**Issue by mlcdev** [kaetemi/ryzomclassic#5]
![screenshot_2019-11-17_003](https://user-images.githubusercontent.com/44550003/69007799-ee604700-0942-11ea-9d1c-d0343e62b987.jpg)

**Comment by kaetemi** [comment]
```
Core was generated by `/home/nevrax/classic/live/service_entities_game_service/entities_game_service -'.
Program terminated with signal SIGILL, Illegal instruction.
#0 0x000055c422912466 in CCharacter::itemBagToExchange (this=0x55c437d7f5d0, bagSlot=10, exchangeSlot=1, quantity=2)
at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character_inventory_manipulation.cpp:1460
#0 0x000055c422912466 in CCharacter::itemBagToExchange (this=0x55c437d7f5d0, bagSlot=10, exchangeSlot=1, quantity=2)
at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/player_manager/character_inventory_manipulation.cpp:1460
#1 0x000055c42219f4c0 in cbClientExchangeAdd (msgin=..., serviceName="FS", serviceId=...) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/client_messages.cpp:1434
#2 0x000055c422b797c5 in CMirror::updateMirrorAndReceiveMessages (this=0x55c42398aac0 <Mirror>, msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2170
#3 0x000055c422b79099 in cbUpdateMirrorAndReceiveMessages (msgin=...) at /mnt/y/ryzomclassic/code/ryzom/common/src/game_share/mirror.cpp:2074
#4 0x000055c422f54a66 in NLNET::uncbMsgProcessing (msgin=..., from=0x7f4f440030c0) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:396
#5 0x000055c422f0d58b in NLNET::CCallbackNetBase::processOneMessage (this=0x55c423e943b0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:216
#6 0x000055c422f0dabe in NLNET::CCallbackNetBase::baseUpdate2 (this=0x55c423e943b0, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_net_base.cpp:411
#7 0x000055c422f0ef88 in NLNET::CCallbackServer::update2 (this=0x55c423e943b0, timeout=99, mintime=0) at /mnt/y/ryzomclassic/code/nel/src/net/callback_server.cpp:137
#8 0x000055c422f58153 in NLNET::CUnifiedNetwork::update (this=0x55c423e83d20, timeout=100) at /mnt/y/ryzomclassic/code/nel/src/net/unified_network.cpp:1052
#9 0x000055c422f3cb8b in NLNET::IService::main (this=0x55c423e7c3d0, serviceShortName=0x55c423046f01 "EGS", serviceLongName=0x55c423046eeb "entities_game_service", servicePort=0,
configDir=0x55c42304495f "", logDir=0x55c42304495f "", compilationDate=0x55c423046f05 "Nov 16 2019 20:16:06") at /mnt/y/ryzomclassic/code/nel/src/net/service.cpp:1401
#10 0x000055c42223e426 in main (argc=5, argv=0x7ffdc6475d78) at /mnt/y/ryzomclassic/code/ryzom/server/src/entities_game_service/entities_game_service.cpp:2138
```

**Comment by kaetemi** [comment]
```
	// check exchange integrity
	bool exchangeWithBot;
	if (!checkExchangeActors(&exchangeWithBot))
	{
		DEBUG_STOP;
		return;
	}
```

**Comment by kaetemi** [comment]
```
2019/11/17 13:02:15 EGS-130 WRN 64871780 character_inventory_manipulation.cpp 1406 : Player (0x0000000024:00:00:86), invalid exchange partner (0x0000000000:ff:00:00)
```

**Comment by kaetemi** [comment]
No longer able to reproduce. May be a rare issue. Need to investigate.

**Comment by kaetemi** [comment]
Can't reproduce. May have been a bad build due to a broken GCC PCH build.
